# Setup
title:               Ben Machlin
tagline:             ''
description:         'Ben Machlin'
url:                 bmack567.github.io
baseurl:             
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ben Machlin
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
